/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package my.ep2;

import javax.swing.JFileChooser;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author JP
 */
public class EP2OCDUI extends javax.swing.JFrame {
    
    /**
     * Creates new form EP2OCDUI
     */
    public EP2OCDUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AXField = new javax.swing.JTextArea();
        LabelAX = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BXField = new javax.swing.JTextArea();
        LabelBX = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CXField = new javax.swing.JTextArea();
        LabelCX = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DXField = new javax.swing.JTextArea();
        LabelDX = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        P1Field = new javax.swing.JTextArea();
        LabelIR = new javax.swing.JLabel();
        LabelOP = new javax.swing.JLabel();
        LabelP1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        OPField = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        P2Field = new javax.swing.JTextArea();
        LabelP2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ULAField = new javax.swing.JTextArea();
        LabelULA = new javax.swing.JLabel();
        LabelMAR = new javax.swing.JLabel();
        LabelMBR = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        MBRField = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        MARField = new javax.swing.JTextArea();
        LabelBInterno = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        BInternoField = new javax.swing.JTextArea();
        LabelPC = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        PCField = new javax.swing.JTextArea();
        LabelULAOP = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ULAOPField = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        ACField = new javax.swing.JTextArea();
        LabelAC = new javax.swing.JLabel();
        LabelX = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        XField = new javax.swing.JTextArea();
        LabelInstruAssembly = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        InstrucaoAssemblyField = new javax.swing.JTextArea();
        AbrirArquivo = new javax.swing.JButton();
        ProxInstru = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        LabelFlagZ = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        LabelFlagS = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        LabelFlagO = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        LabelFlags = new javax.swing.JLabel();
        LabelTempo = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        TEMPOField = new javax.swing.JTextArea();
        LabelBExterno = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        LabelAV = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        AVField = new javax.swing.JTextArea();
        LabelRead = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        READField = new javax.swing.JTextArea();
        LabelWrite = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        WRITEField = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        endereco_arquivo_l = new javax.swing.JTextArea();
        LabelLocali = new javax.swing.JLabel();
//        retorno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EP2 OCD");
        setMinimumSize(new java.awt.Dimension(749, 341));
        setResizable(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setName("AX"); // NOI18N
        jScrollPane1.setOpaque(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        AXField.setEditable(false);
        AXField.setColumns(20);
        AXField.setRows(5);
        AXField.setText("AX");
        AXField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AXField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(AXField);

        LabelAX.setBackground(new java.awt.Color(0, 0, 204));
        LabelAX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAX.setText("AX");
        LabelAX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setName("AX"); // NOI18N
        jScrollPane2.setOpaque(false);
        jScrollPane2.setWheelScrollingEnabled(false);

        BXField.setEditable(false);
        BXField.setColumns(20);
        BXField.setRows(5);
        BXField.setText("BX");
        BXField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BXField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(BXField);

        LabelBX.setBackground(new java.awt.Color(0, 0, 204));
        LabelBX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBX.setText("BX");
        LabelBX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setName("AX"); // NOI18N
        jScrollPane3.setOpaque(false);
        jScrollPane3.setWheelScrollingEnabled(false);

        CXField.setEditable(false);
        CXField.setColumns(20);
        CXField.setRows(5);
        CXField.setText("CX");
        CXField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CXField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(CXField);

        LabelCX.setBackground(new java.awt.Color(0, 0, 204));
        LabelCX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCX.setText("CX");
        LabelCX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setName("AX"); // NOI18N
        jScrollPane4.setOpaque(false);
        jScrollPane4.setWheelScrollingEnabled(false);

        DXField.setEditable(false);
        DXField.setColumns(20);
        DXField.setRows(5);
        DXField.setText("DX");
        DXField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DXField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(DXField);

        LabelDX.setBackground(new java.awt.Color(0, 0, 204));
        LabelDX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDX.setText("DX");
        LabelDX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setName("AX"); // NOI18N
        jScrollPane5.setOpaque(false);
        jScrollPane5.setWheelScrollingEnabled(false);

        P1Field.setEditable(false);
        P1Field.setColumns(20);
        P1Field.setRows(5);
        P1Field.setText("P1");
        P1Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P1Field.setCaretColor(new java.awt.Color(255, 255, 255));
        P1Field.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(P1Field);

        LabelIR.setBackground(new java.awt.Color(102, 0, 0));
        LabelIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIR.setText("IR");
        LabelIR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelOP.setBackground(new java.awt.Color(102, 0, 0));
        LabelOP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOP.setText("OP");
        LabelOP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelP1.setBackground(new java.awt.Color(102, 0, 0));
        LabelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelP1.setText("P1");
        LabelP1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane6.setName("AX"); // NOI18N
        jScrollPane6.setOpaque(false);
        jScrollPane6.setWheelScrollingEnabled(false);

        OPField.setEditable(false);
        OPField.setColumns(20);
        OPField.setRows(5);
        OPField.setText("NADA");
        OPField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OPField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(OPField);

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane7.setName("AX"); // NOI18N
        jScrollPane7.setOpaque(false);
        jScrollPane7.setWheelScrollingEnabled(false);

        P2Field.setEditable(false);
        P2Field.setColumns(20);
        P2Field.setRows(5);
        P2Field.setText("P2");
        P2Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P2Field.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane7.setViewportView(P2Field);

        LabelP2.setBackground(new java.awt.Color(102, 0, 0));
        LabelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelP2.setText("P2");
        LabelP2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setName("AX"); // NOI18N
        jScrollPane8.setOpaque(false);
        jScrollPane8.setWheelScrollingEnabled(false);

        ULAField.setEditable(false);
        ULAField.setColumns(20);
        ULAField.setRows(5);
        ULAField.setText("ULA");
        ULAField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ULAField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(ULAField);

        LabelULA.setBackground(new java.awt.Color(0, 102, 102));
        LabelULA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelULA.setText("ULA");
        LabelULA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelMAR.setBackground(new java.awt.Color(102, 102, 0));
        LabelMAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMAR.setText("MAR");
        LabelMAR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelMBR.setBackground(new java.awt.Color(102, 102, 0));
        LabelMBR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMBR.setText("MBR");
        LabelMBR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane10.setBorder(null);
        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane10.setName("AX"); // NOI18N
        jScrollPane10.setOpaque(false);
        jScrollPane10.setWheelScrollingEnabled(false);

        MBRField.setEditable(false);
        MBRField.setColumns(20);
        MBRField.setRows(5);
        MBRField.setText("MBR");
        MBRField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MBRField.setCaretColor(new java.awt.Color(255, 255, 255));
        MBRField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane10.setViewportView(MBRField);

        jScrollPane11.setBorder(null);
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane11.setName("AX"); // NOI18N
        jScrollPane11.setOpaque(false);
        jScrollPane11.setWheelScrollingEnabled(false);

        MARField.setEditable(false);
        MARField.setColumns(20);
        MARField.setRows(5);
        MARField.setText("MAR");
        MARField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MARField.setCaretColor(new java.awt.Color(255, 255, 255));
        MARField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane11.setViewportView(MARField);

        LabelBInterno.setBackground(new java.awt.Color(102, 102, 0));
        LabelBInterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBInterno.setText("B. Interno");
        LabelBInterno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane12.setBorder(null);
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane12.setName("AX"); // NOI18N
        jScrollPane12.setOpaque(false);
        jScrollPane12.setWheelScrollingEnabled(false);

        BInternoField.setEditable(false);
        BInternoField.setColumns(20);
        BInternoField.setRows(5);
        BInternoField.setText("Barramento Interno");
        BInternoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BInternoField.setCaretColor(new java.awt.Color(255, 255, 255));
        BInternoField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane12.setViewportView(BInternoField);

        LabelPC.setBackground(new java.awt.Color(102, 102, 0));
        LabelPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPC.setText("PC");
        LabelPC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane13.setBorder(null);
        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane13.setName("AX"); // NOI18N
        jScrollPane13.setOpaque(false);
        jScrollPane13.setWheelScrollingEnabled(false);

        PCField.setEditable(false);
        PCField.setColumns(20);
        PCField.setRows(5);
        PCField.setText("NADA");
        PCField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PCField.setCaretColor(new java.awt.Color(255, 255, 255));
        PCField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane13.setViewportView(PCField);

        LabelULAOP.setBackground(new java.awt.Color(0, 102, 102));
        LabelULAOP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelULAOP.setText("ULA OP");
        LabelULAOP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane9.setBorder(null);
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane9.setName("AX"); // NOI18N
        jScrollPane9.setOpaque(false);
        jScrollPane9.setWheelScrollingEnabled(false);

        ULAOPField.setEditable(false);
        ULAOPField.setColumns(20);
        ULAOPField.setRows(5);
        ULAOPField.setText("NADA");
        ULAOPField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ULAOPField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane9.setViewportView(ULAOPField);

        jScrollPane14.setBorder(null);
        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane14.setName("AX"); // NOI18N
        jScrollPane14.setOpaque(false);
        jScrollPane14.setWheelScrollingEnabled(false);

        ACField.setEditable(false);
        ACField.setColumns(20);
        ACField.setRows(5);
        ACField.setText("NADA");
        ACField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ACField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane14.setViewportView(ACField);

        LabelAC.setBackground(new java.awt.Color(0, 102, 102));
        LabelAC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAC.setText("AC");
        LabelAC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelX.setBackground(new java.awt.Color(0, 102, 102));
        LabelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelX.setText("X");
        LabelX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane15.setBorder(null);
        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane15.setName("AX"); // NOI18N
        jScrollPane15.setOpaque(false);
        jScrollPane15.setWheelScrollingEnabled(false);

        XField.setEditable(false);
        XField.setColumns(20);
        XField.setRows(5);
        XField.setText("NADA");
        XField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        XField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane15.setViewportView(XField);

        LabelInstruAssembly.setBackground(new java.awt.Color(102, 0, 0));
        LabelInstruAssembly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInstruAssembly.setText("INSTRUÇÃO ASSEMBLY");
        LabelInstruAssembly.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane16.setBorder(null);
        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane16.setName("AX"); // NOI18N
        jScrollPane16.setOpaque(false);
        jScrollPane16.setWheelScrollingEnabled(false);

        InstrucaoAssemblyField.setEditable(false);
        InstrucaoAssemblyField.setColumns(20);
        InstrucaoAssemblyField.setRows(5);
        InstrucaoAssemblyField.setText("Ignora");
        InstrucaoAssemblyField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InstrucaoAssemblyField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        InstrucaoAssemblyField.setOpaque(false);
        jScrollPane16.setViewportView(InstrucaoAssemblyField);

        AbrirArquivo.setText("Abrir");
        AbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirArquivoActionPerformed(evt);
            }
        });

        ProxInstru.setText("Próxima micro-instrução");
        ProxInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProxInstruActionPerformed(evt);
            }
        });

        LabelFlagZ.setBackground(new java.awt.Color(51, 102, 0));
        LabelFlagZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFlagZ.setText("Z");
        LabelFlagZ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane17.setBorder(null);
        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane17.setName("AX"); // NOI18N
        jScrollPane17.setOpaque(false);
        jScrollPane17.setWheelScrollingEnabled(false);

        jTextArea17.setEditable(false);
        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("0");
        jTextArea17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea17.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane17.setViewportView(jTextArea17);

        LabelFlagS.setBackground(new java.awt.Color(51, 102, 0));
        LabelFlagS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFlagS.setText("S");
        LabelFlagS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane18.setBorder(null);
        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane18.setName("AX"); // NOI18N
        jScrollPane18.setOpaque(false);
        jScrollPane18.setWheelScrollingEnabled(false);

        jTextArea18.setEditable(false);
        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("0");
        jTextArea18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea18.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane18.setViewportView(jTextArea18);

        LabelFlagO.setBackground(new java.awt.Color(51, 102, 0));
        LabelFlagO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFlagO.setText("O");
        LabelFlagO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane19.setBorder(null);
        jScrollPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane19.setName("AX"); // NOI18N
        jScrollPane19.setOpaque(false);
        jScrollPane19.setWheelScrollingEnabled(false);

        jTextArea19.setEditable(false);
        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("0");
        jTextArea19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea19.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane19.setViewportView(jTextArea19);

        LabelFlags.setBackground(new java.awt.Color(51, 102, 0));
        LabelFlags.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFlags.setText("FLAGS");
        LabelFlags.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelTempo.setBackground(new java.awt.Color(51, 102, 0));
        LabelTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTempo.setText("TEMPO");
        LabelTempo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane20.setBorder(null);
        jScrollPane20.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane20.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane20.setName("AX"); // NOI18N
        jScrollPane20.setOpaque(false);
        jScrollPane20.setWheelScrollingEnabled(false);

        TEMPOField.setEditable(false);
        TEMPOField.setColumns(20);
        TEMPOField.setRows(5);
        TEMPOField.setText("NADA");
        TEMPOField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TEMPOField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane20.setViewportView(TEMPOField);

        LabelBExterno.setBackground(new java.awt.Color(102, 102, 0));
        LabelBExterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBExterno.setText("B. Externo");
        LabelBExterno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane21.setBorder(null);
        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane21.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane21.setName("AX"); // NOI18N
        jScrollPane21.setOpaque(false);
        jScrollPane21.setWheelScrollingEnabled(false);

        jTextArea21.setEditable(false);
        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("Barramento Externo");
        jTextArea21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea21.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea21.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane21.setViewportView(jTextArea21);

        LabelAV.setBackground(new java.awt.Color(102, 102, 0));
        LabelAV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAV.setText("AV");
        LabelAV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane22.setBorder(null);
        jScrollPane22.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane22.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane22.setName("AX"); // NOI18N
        jScrollPane22.setOpaque(false);
        jScrollPane22.setWheelScrollingEnabled(false);

        AVField.setEditable(false);
        AVField.setColumns(20);
        AVField.setRows(5);
        AVField.setText("NADA");
        AVField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AVField.setCaretColor(new java.awt.Color(255, 255, 255));
        AVField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane22.setViewportView(AVField);

        LabelRead.setBackground(new java.awt.Color(102, 102, 0));
        LabelRead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRead.setText("READ");
        LabelRead.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane23.setBorder(null);
        jScrollPane23.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane23.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane23.setName("AX"); // NOI18N
        jScrollPane23.setOpaque(false);
        jScrollPane23.setWheelScrollingEnabled(false);

        READField.setEditable(false);
        READField.setColumns(20);
        READField.setRows(5);
        READField.setText("NADA");
        READField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        READField.setCaretColor(new java.awt.Color(255, 255, 255));
        READField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane23.setViewportView(READField);

        LabelWrite.setBackground(new java.awt.Color(102, 102, 0));
        LabelWrite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelWrite.setText("WRITE");
        LabelWrite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane24.setBorder(null);
        jScrollPane24.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane24.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane24.setName("AX"); // NOI18N
        jScrollPane24.setOpaque(false);
        jScrollPane24.setWheelScrollingEnabled(false);

        WRITEField.setEditable(false);
        WRITEField.setColumns(20);
        WRITEField.setRows(5);
        WRITEField.setText("NADA");
        WRITEField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WRITEField.setCaretColor(new java.awt.Color(255, 255, 255));
        WRITEField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane24.setViewportView(WRITEField);

        jScrollPane26.setBorder(null);
        jScrollPane26.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane26.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane26.setName("AX"); // NOI18N
        jScrollPane26.setOpaque(false);
        jScrollPane26.setWheelScrollingEnabled(false);

        endereco_arquivo_l.setEditable(false);
        endereco_arquivo_l.setColumns(20);
        endereco_arquivo_l.setRows(5);
        endereco_arquivo_l.setText("*Sem arquivo aberto no momento!");
        endereco_arquivo_l.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        endereco_arquivo_l.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        endereco_arquivo_l.setOpaque(false);
        jScrollPane26.setViewportView(endereco_arquivo_l);

        LabelLocali.setText("Localização");

//        retorno.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AbrirArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProxInstru)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelDX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(LabelCX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelBX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFlags, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelFlagZ, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelFlagS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LabelFlagO, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane16)
                                            .addComponent(LabelInstruAssembly, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelAV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabelRead, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabelWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelBExterno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(LabelOP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane5)
                                            .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelULAOP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelULA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelAC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelBInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelMBR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelMAR, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addComponent(LabelIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelLocali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
//                .addComponent(retorno, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProxInstru)
                    .addComponent(AbrirArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelIR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelOP)
                                .addComponent(LabelP1))
                            .addComponent(LabelP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelAC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LabelBInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelULAOP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelMBR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelULA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(LabelInstruAssembly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelBExterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelAV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelRead, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(LabelAX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(LabelBX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(LabelCX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(LabelDX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(LabelFlags)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFlagO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelFlagZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelFlagS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(retorno, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(LabelLocali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String[] linesArray; //cada elemento da array representa uma linha do arquivo de entrada txt
    private int lineIndex = 0;
    private boolean inicializa = true;
    Principal UC_firmware;
    
    private void AbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirArquivoActionPerformed
        // Abrir
        JFileChooser arquivo = new JFileChooser();
        if(arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            endereco_arquivo_l.setText(arquivo.getSelectedFile().getAbsolutePath());
            try{
                this.lineIndex = 0;
                BufferedReader arquivoTxt = new BufferedReader(new FileReader(arquivo.getSelectedFile().getAbsolutePath()));
                List<String> lines = new ArrayList<String>();
                String line;
                //MEMORIA
                MemoriaRAM memoriaRam = new MemoriaRAM();
                
                
                while((line = arquivoTxt.readLine()) != null) {
                    lines.add(line);
                    try{
                        memoriaRam.add(line);
                    }
                    catch(Exception b){
                        System.out.println("Error: "+line);
                    }
                }
                memoriaRam.printaHash();
                
                //System.out.println("get "+memoriaRam.get("6"));
                
                arquivoTxt.close();
                this.linesArray = lines.toArray(new String[]{});
                MemoriaChip.popularMemoriaChip();
                UC_firmware = new Principal(memoriaRam);
                inicializa = false;
            }
            catch(Exception e){
//                retorno.setText("Erro");
            }
        }
    }//GEN-LAST:event_AbrirArquivoActionPerformed
    
    
    private void ProxInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProxInstruActionPerformed
        //CHECA SE ACABOU AS LINHAS
        
        /*
        while(this.lineIndex < this.linesArray.length && this.linesArray[this.lineIndex].contains(":")) this.lineIndex++;
        if (this.lineIndex >= this.linesArray.length)
        {
            InstrucaoAssemblyField.setText("");
            retorno.setText("Fim");
            return;
        }
        InstrucaoAssemblyField.setText(getInstruction(this.linesArray[this.lineIndex]));
        retorno.setText(this.linesArray[this.lineIndex]);
        //LEITURA DA LINHA
        
        this.lineIndex++;
        
        */
        
        if(inicializa) return; // Nao abriu o arquivo ainda!
        UC_firmware.ButtonClick();
        
        MemoriaRAM rm = (MemoriaRAM)Principal.Componentes[13];
        //john
        AVField.setText("         " +boolToString(rm.adress_valid));
        READField.setText("        " +boolToString(rm.read));
        WRITEField.setText("          " +boolToString(rm.write));
        P1Field.setText(Principal.Componentes[9].Get());
        P2Field.setText(Principal.Componentes[10].Get());
        OPField.setText(((IR)Principal.Componentes[8]).getUpcode());
        BInternoField.setText(BarramentoInterno.Get());
        jTextArea21.setText(BarramentoExterno.Get());
        AXField.setText(Principal.Componentes[3].Get());
        BXField.setText(Principal.Componentes[4].Get());
        CXField.setText(Principal.Componentes[5].Get());
        DXField.setText(Principal.Componentes[6].Get());
        TEMPOField.setText(((Integer)Principal.t).toString());
        PCField.setText(Principal.Componentes[0].Get());
        MARField.setText(Principal.Componentes[1].Get());
        MBRField.setText(Principal.Componentes[2].Get());
        XField.setText(Principal.Componentes[11].Get());
        ULAField.setText(Principal.Componentes[12].Get());
        ULAOPField.setText(((ULA)Principal.Componentes[12]).GetUpcode());
        ACField.setText(((ULA)Principal.Componentes[12]).AC_.GetACUI());
        jTextArea18.setText(boolToString(((ULA)Principal.Componentes[12]).negative)); // negativo
        jTextArea19.setText(boolToString(((ULA)Principal.Componentes[12]).overflow)); // overflow
        jTextArea17.setText(boolToString(((ULA)Principal.Componentes[12]).zero)); // zero
        //rm.printaHash();
       // System.out.println();
    }//GEN-LAST:event_ProxInstruActionPerformed
    
    String boolToString(boolean b)
    {
        if(b) return "1";
        return "0";
    }
    
    private String getInstruction(String line){
        String[] opcodesInstrucao = { "MOV", "ADD", "SUB", "MUL", "DIV", "MOD", "CMP", "JMP", "JE", "JNE", "JG", "JGE", "JGL", "JLE"};
        //remove o espaco anterior a intrucao
        String noTabLine = "";
        for (int i = 1; i < line.length(); i++){
            if (!line.substring(i, i+2).contains(" ") && !line.substring(i, i+2).contains("   "))
            {
                noTabLine = line.substring(i);
                break;
            }
        }
        
        String[] lineSplitted = noTabLine.split(" ");

        for (int i = 0; i < opcodesInstrucao.length; i++){
            if (lineSplitted[0].equals(opcodesInstrucao[i]))
            {
               return opcodesInstrucao[i];
            }
        }
        
        return "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EP2OCDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EP2OCDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EP2OCDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EP2OCDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EP2OCDUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ACField;
    private javax.swing.JTextArea AVField;
    private javax.swing.JTextArea AXField;
    private javax.swing.JButton AbrirArquivo;
    private javax.swing.JTextArea BInternoField;
    private javax.swing.JTextArea BXField;
    private javax.swing.JTextArea CXField;
    private javax.swing.JTextArea DXField;
    private javax.swing.JTextArea InstrucaoAssemblyField;
    private javax.swing.JLabel LabelAC;
    private javax.swing.JLabel LabelAV;
    private javax.swing.JLabel LabelAX;
    private javax.swing.JLabel LabelBExterno;
    private javax.swing.JLabel LabelBInterno;
    private javax.swing.JLabel LabelBX;
    private javax.swing.JLabel LabelCX;
    private javax.swing.JLabel LabelDX;
    private javax.swing.JLabel LabelFlagO;
    private javax.swing.JLabel LabelFlagS;
    private javax.swing.JLabel LabelFlagZ;
    private javax.swing.JLabel LabelFlags;
    private javax.swing.JLabel LabelIR;
    private javax.swing.JLabel LabelInstruAssembly;
    private javax.swing.JLabel LabelLocali;
    private javax.swing.JLabel LabelMAR;
    private javax.swing.JLabel LabelMBR;
    private javax.swing.JLabel LabelOP;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    private javax.swing.JLabel LabelPC;
    private javax.swing.JLabel LabelRead;
    private javax.swing.JLabel LabelTempo;
    private javax.swing.JLabel LabelULA;
    private javax.swing.JLabel LabelULAOP;
    private javax.swing.JLabel LabelWrite;
    private javax.swing.JLabel LabelX;
    private javax.swing.JTextArea MARField;
    private javax.swing.JTextArea MBRField;
    private javax.swing.JTextArea OPField;
    private javax.swing.JTextArea P1Field;
    private javax.swing.JTextArea P2Field;
    private javax.swing.JTextArea PCField;
    private javax.swing.JButton ProxInstru;
    private javax.swing.JTextArea READField;
    private javax.swing.JTextArea TEMPOField;
    private javax.swing.JTextArea ULAField;
    private javax.swing.JTextArea ULAOPField;
    private javax.swing.JTextArea WRITEField;
    private javax.swing.JTextArea XField;
    private javax.swing.JTextArea endereco_arquivo_l;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextField retorno;
    // End of variables declaration//GEN-END:variables
    
    private void setRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
